version: "3.0"
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dummy
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --collation-server=utf8_unicode_ci --character-set-server=utf8
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  backup_restore:
    image: backup_restore
    volumes:
      - ./${PYTEST_BACKUP_DIR}:/backup
      - mysql_data:/var/lib/backup/mysql
    command: backup
  zhdun:
    image: zhdun
volumes:
  mysql_data:
    external: true
